// _EditorStoredProcedure_EOArchive_English.java
// Generated by EnterpriseObjects palette at Wednesday, October 13, 2004 3:01:45 PM US/Central

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.eointerface.swing.EOTable._EOTableColumn;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _EditorStoredProcedure_EOArchive_English extends com.webobjects.eoapplication.EOArchive {
    com.webobjects.eointerface.swing.EOTable _nsTableView0;
    com.webobjects.eointerface.swing.EOTable._EOTableColumn _eoTableColumn0, _eoTableColumn1, _eoTableColumn2, _eoTableColumn3, _eoTableColumn4, _eoTableColumn5, _eoTableColumn6, _eoTableColumn7, _eoTableColumn8;
    com.webobjects.eointerface.swing.EOTextField _eoTextField0, _eoTextField1;
    com.webobjects.eointerface.swing.EOView _nsCustomView0;
    com.webobjects.foundation.NSNumberFormatter _nsNumberFormatter0, _nsNumberFormatter1, _nsNumberFormatter2;
    javax.swing.JButton _jButton0;

    public _EditorStoredProcedure_EOArchive_English(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _eoTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _jButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "");
        _nsNumberFormatter2 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("#,##0;-#,##0"), "");
        _nsNumberFormatter1 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("#,##0;-#,##0"), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "view")) != null)) {
            _nsCustomView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView0");
        } else {
            _nsCustomView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "View");
        }

        _eoTableColumn8 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn7 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn6 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn5 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn4 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "procedureTable")) != null)) {
            _nsTableView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTable)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTableView0");
        } else {
            _nsTableView0 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "NSTableView");
        }

        _nsNumberFormatter0 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("#,##0;-#,##0"), "");
        _eoTableColumn3 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn2 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTableColumn1 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn0 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
    }

    protected void _awaken() {
        super._awaken();
        _nsTableView0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "selectedArgument", _nsTableView0), ""));

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _connect(_nsTableView0, _owner(), "delegate");
        }

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _connect(_owner(), _nsTableView0, "procedureTable");
        }

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            _connect(_owner(), _nsCustomView0, "view");
        }

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _connect(_nsTableView0, _owner(), "dataSource");
        }
    }

    protected void _init() {
        super._init();
        _setFontForComponent(_eoTextField1, "Lucida Grande", 12, Font.PLAIN);
        _setFontForComponent(_jButton0, "Lucida Grande", 11, Font.PLAIN);
        _jButton0.setMargin(new Insets(0, 2, 0, 2));
        
        

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            if (!(_nsCustomView0.getLayout() instanceof EOViewLayout)) { _nsCustomView0.setLayout(new EOViewLayout()); }
            _nsTableView0.setSize(613, 647);
            _nsTableView0.setLocation(0, 0);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTableView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
            _nsCustomView0.add(_nsTableView0);
        }

        _eoTableColumn8.setMinWidth(10);
        _eoTableColumn8.setMaxWidth(1000);
        _eoTableColumn8.setPreferredWidth(66);
        _eoTableColumn8.setWidth(66);
        _eoTableColumn8.setResizable(true);
        _eoTableColumn8.setHeaderValue("Value Type");
        if ((_eoTableColumn8.getCellRenderer() instanceof DefaultTableCellRenderer) || (_eoTableColumn8.getCellRenderer() == null)) {
        	DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        	renderer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        	_eoTableColumn8.setCellRenderer(renderer);
        }
        _eoTableColumn7.setMinWidth(10);
        _eoTableColumn7.setMaxWidth(1000);
        _eoTableColumn7.setPreferredWidth(48);
        _eoTableColumn7.setWidth(48);
        _eoTableColumn7.setResizable(true);
        _eoTableColumn7.setHeaderValue("Precision");
        if ((_eoTableColumn7.getCellRenderer() instanceof DefaultTableCellRenderer) || (_eoTableColumn7.getCellRenderer() == null)) {
        	DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        	renderer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        	_eoTableColumn7.setCellRenderer(renderer);
        }
        _eoTableColumn6.setMinWidth(10);
        _eoTableColumn6.setMaxWidth(1000);
        _eoTableColumn6.setPreferredWidth(72);
        _eoTableColumn6.setWidth(72);
        _eoTableColumn6.setResizable(true);
        _eoTableColumn6.setHeaderValue("External Type");
        _eoTableColumn5.setMinWidth(10);
        _eoTableColumn5.setMaxWidth(1000);
        _eoTableColumn5.setPreferredWidth(72);
        _eoTableColumn5.setWidth(72);
        _eoTableColumn5.setResizable(true);
        _eoTableColumn5.setHeaderValue("Value Class");
        _eoTableColumn4.setMinWidth(10);
        _eoTableColumn4.setMaxWidth(1000);
        _eoTableColumn4.setPreferredWidth(108);
        _eoTableColumn4.setWidth(108);
        _eoTableColumn4.setResizable(true);
        _eoTableColumn4.setHeaderValue("Name");

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _nsTableView0.table().addColumn(_eoTableColumn4);
            _nsTableView0.table().addColumn(_eoTableColumn3);
            _nsTableView0.table().addColumn(_eoTableColumn2);
            _nsTableView0.table().addColumn(_eoTableColumn5);
            _nsTableView0.table().addColumn(_eoTableColumn6);
            _nsTableView0.table().addColumn(_eoTableColumn1);
            _nsTableView0.table().addColumn(_eoTableColumn0);
            _nsTableView0.table().addColumn(_eoTableColumn7);
            _nsTableView0.table().addColumn(_eoTableColumn8);
            _setFontForComponent(_nsTableView0.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
            _nsTableView0.table().setRowHeight(17);
        }

        
        _eoTableColumn3.setMinWidth(10);
        _eoTableColumn3.setMaxWidth(1000);
        _eoTableColumn3.setPreferredWidth(108);
        _eoTableColumn3.setWidth(108);
        _eoTableColumn3.setResizable(true);
        _eoTableColumn3.setHeaderValue("Column");
        _eoTableColumn2.setMinWidth(10);
        _eoTableColumn2.setMaxWidth(1000);
        _eoTableColumn2.setPreferredWidth(72);
        _eoTableColumn2.setWidth(72);
        _eoTableColumn2.setResizable(true);
        _eoTableColumn2.setHeaderValue("Direction");
        _setFontForComponent(_eoTextField0, "Lucida Grande", 12, Font.PLAIN);
        _eoTableColumn1.setMinWidth(10);
        _eoTableColumn1.setMaxWidth(1000);
        _eoTableColumn1.setPreferredWidth(48);
        _eoTableColumn1.setWidth(48);
        _eoTableColumn1.setResizable(true);
        _eoTableColumn1.setHeaderValue("Width");
        if ((_eoTableColumn1.getCellRenderer() instanceof DefaultTableCellRenderer) || (_eoTableColumn1.getCellRenderer() == null)) {
        	DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        	renderer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        	_eoTableColumn1.setCellRenderer(renderer);
        }
        _eoTableColumn0.setMinWidth(10);
        _eoTableColumn0.setMaxWidth(1000);
        _eoTableColumn0.setPreferredWidth(48);
        _eoTableColumn0.setWidth(48);
        _eoTableColumn0.setResizable(true);
        _eoTableColumn0.setHeaderValue("Scale");
        if ((_eoTableColumn0.getCellRenderer() instanceof DefaultTableCellRenderer) || (_eoTableColumn0.getCellRenderer() == null)) {
        	DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        	renderer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        	_eoTableColumn0.setCellRenderer(renderer);
        }
    }
}
