// _EditorEntities_EOArchive_English.java
// Generated by EnterpriseObjects palette at Thursday, September 30, 2004 3:45:38 PM US/Central

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.eointerface.swing.EOTable._EOTableColumn;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _EditorEntities_EOArchive_English extends com.webobjects.eoapplication.EOArchive {
    com.webobjects.eointerface.swing.EOTable _nsTableView0;
    com.webobjects.eointerface.swing.EOTable._EOTableColumn _eoTableColumn0, _eoTableColumn1, _eoTableColumn2, _eoTableColumn3, _eoTableColumn4, _eoTableColumn5, _eoTableColumn6, _eoTableColumn7;
    com.webobjects.eointerface.swing.EOView _nsCustomView0;
    javax.swing.JCheckBox _jCheckBox0, _jCheckBox1, _jCheckBox2;

    public _EditorEntities_EOArchive_English(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _jCheckBox2 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox(""), "");
        _jCheckBox1 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox(""), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "view")) != null)) {
            _nsCustomView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView0");
        } else {
            _nsCustomView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "View");
        }

        _eoTableColumn7 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn6 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn5 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "entityTable")) != null)) {
            _nsTableView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTable)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTableView0");
        } else {
            _nsTableView0 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "NSTableView");
        }

        _eoTableColumn4 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn3 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _jCheckBox0 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox(""), "");
        _eoTableColumn2 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn1");
        _eoTableColumn1 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn0 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
    }

    protected void _awaken() {
        super._awaken();
        _nsTableView0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "selectEntity", _nsTableView0), ""));

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _connect(_nsTableView0, _owner(), "delegate");
        }

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _connect(_owner(), _nsTableView0, "entityTable");
        }

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            _connect(_owner(), _nsCustomView0, "view");
        }

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _connect(_nsTableView0, _owner(), "dataSource");
        }
    }

    protected void _init() {
        super._init();
        _setFontForComponent(_jCheckBox2, "Lucida Grande", 12, Font.PLAIN);
        _setFontForComponent(_jCheckBox1, "Lucida Grande", 12, Font.PLAIN);

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            if (!(_nsCustomView0.getLayout() instanceof EOViewLayout)) { _nsCustomView0.setLayout(new EOViewLayout()); }
            _nsTableView0.setSize(613, 647);
            _nsTableView0.setLocation(0, 0);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTableView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
            _nsCustomView0.add(_nsTableView0);
        }

        _eoTableColumn7.setMinWidth(75);
        _eoTableColumn7.setMaxWidth(1000);
        _eoTableColumn7.setPreferredWidth(80);
        _eoTableColumn7.setWidth(80);
        _eoTableColumn7.setResizable(true);
        _eoTableColumn7.setHeaderValue("Parent Entity");
        _eoTableColumn6.setMinWidth(10);
        _eoTableColumn6.setMaxWidth(20);
        _eoTableColumn6.setPreferredWidth(20);
        _eoTableColumn6.setWidth(20);
        _eoTableColumn6.setResizable(true);
        _eoTableColumn6.setHeaderValue("Caches Objects");
        _eoTableColumn5.setMinWidth(40);
        _eoTableColumn5.setMaxWidth(1000);
        _eoTableColumn5.setPreferredWidth(108);
        _eoTableColumn5.setWidth(108);
        _eoTableColumn5.setResizable(true);
        _eoTableColumn5.setHeaderValue("Name");

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _nsTableView0.table().addColumn(_eoTableColumn5);
            _nsTableView0.table().addColumn(_eoTableColumn2);
            _nsTableView0.table().addColumn(_eoTableColumn3);
            _nsTableView0.table().addColumn(_eoTableColumn1);
            _nsTableView0.table().addColumn(_eoTableColumn6);
            _nsTableView0.table().addColumn(_eoTableColumn4);
            _nsTableView0.table().addColumn(_eoTableColumn0);
            _nsTableView0.table().addColumn(_eoTableColumn7);
            _setFontForComponent(_nsTableView0.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
            _nsTableView0.table().setRowHeight(17);
        }

        _eoTableColumn4.setMinWidth(10);
        _eoTableColumn4.setMaxWidth(1000);
        _eoTableColumn4.setPreferredWidth(108);
        _eoTableColumn4.setWidth(108);
        _eoTableColumn4.setResizable(true);
        _eoTableColumn4.setHeaderValue("Class Name");
        _eoTableColumn3.setMinWidth(10);
        _eoTableColumn3.setMaxWidth(20);
        _eoTableColumn3.setPreferredWidth(20);
        _eoTableColumn3.setWidth(20);
        _eoTableColumn3.setResizable(true);
        _eoTableColumn3.setHeaderValue("Read Only");
        _setFontForComponent(_jCheckBox0, "Lucida Grande", 12, Font.PLAIN);
        _eoTableColumn2.setMinWidth(8);
        _eoTableColumn2.setMaxWidth(1000);
        _eoTableColumn2.setPreferredWidth(108);
        _eoTableColumn2.setWidth(108);
        _eoTableColumn2.setResizable(true);
        _eoTableColumn2.setHeaderValue("Table");
        _eoTableColumn1.setMinWidth(10);
        _eoTableColumn1.setMaxWidth(20);
        _eoTableColumn1.setPreferredWidth(20);
        _eoTableColumn1.setWidth(20);
        _eoTableColumn1.setResizable(true);
        _eoTableColumn1.setHeaderValue("Abstract Entity");
        _eoTableColumn0.setMinWidth(10);
        _eoTableColumn0.setMaxWidth(1000);
        _eoTableColumn0.setPreferredWidth(108);
        _eoTableColumn0.setWidth(108);
        _eoTableColumn0.setResizable(true);
        _eoTableColumn0.setHeaderValue("External Query");
    }
}
