// _PostgreSQLConnectionPane_EOArchive_English.java
// Generated by EnterpriseObjects palette at Thursday, October 7, 2004 1:35:13 PM US/Central

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _PostgreSQLConnectionPane_EOArchive_English extends com.webobjects.eoapplication.EOArchive {
    com.webobjects.eointerface.swing.EOTextField _nsTextField0, _nsTextField1, _nsTextField10, _nsTextField11, _nsTextField12, _nsTextField13, _nsTextField14, _nsTextField15, _nsTextField16, _nsTextField17, _nsTextField2, _nsTextField3, _nsTextField4, _nsTextField5, _nsTextField6, _nsTextField7, _nsTextField8, _nsTextField9;
    com.webobjects.eointerface.swing.EOView _nsCustomView0, _nsCustomView1;
    javax.swing.JPasswordField _nsTextField18, _nsTextField19;

    public _PostgreSQLConnectionPane_EOArchive_English(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _nsTextField17 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField21");
        _nsTextField16 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField211");
        _nsTextField15 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");
        _nsTextField14 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2121");
        _nsTextField13 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField212");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "smallHostNameField.nextFocusableComponent")) != null)) {
            _nsTextField12 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField12");
        } else {
            _nsTextField12 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "smallUserNameField.nextFocusableComponent.nextFocusableComponent.nextFocusableComponent")) != null)) {
            _nsTextField11 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField11");
        } else {
            _nsTextField11 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField");
        }

        _nsTextField10 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2121");
        _nsTextField9 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField212");
        _nsTextField8 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField211");
        _nsTextField7 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField21");
        _nsTextField6 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "hostNameField.nextFocusableComponent.nextFocusableComponent.nextFocusableComponent.nextFocusableComponent.nextFocusableComponent")) != null)) {
            _nsCustomView1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView1");
        } else {
            _nsCustomView1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "View");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "hostNameField.nextFocusableComponent.nextFocusableComponent.nextFocusableComponent.nextFocusableComponent")) != null)) {
            _nsTextField19 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JPasswordField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField19");
        } else {
            _nsTextField19 = (javax.swing.JPasswordField)_registered(new javax.swing.JPasswordField(), "NSTextField121");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "hostNameField.nextFocusableComponent.nextFocusableComponent.nextFocusableComponent")) != null)) {
            _nsTextField5 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField5");
        } else {
            _nsTextField5 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField12");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "hostNameField.nextFocusableComponent.nextFocusableComponent")) != null)) {
            _nsTextField4 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField4");
        } else {
            _nsTextField4 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "hostNameField.nextFocusableComponent")) != null)) {
            _nsTextField3 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField3");
        } else {
            _nsTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "hostNameField.nextFocusableComponent.nextFocusableComponent.nextFocusableComponent.nextFocusableComponent.nextFocusableComponent.nextFocusableComponent")) != null)) {
            _nsTextField2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField2");
        } else {
            _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "smallHostNameField.nextFocusableComponent.nextFocusableComponent")) != null)) {
            _nsTextField1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField1");
        } else {
            _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "smallUserNameField.nextFocusableComponent.nextFocusableComponent")) != null)) {
            _nsCustomView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView0");
        } else {
            _nsCustomView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "PSQL Small View");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "smallUserNameField.nextFocusableComponent")) != null)) {
            _nsTextField18 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JPasswordField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField18");
        } else {
            _nsTextField18 = (javax.swing.JPasswordField)_registered(new javax.swing.JPasswordField(), "NSTextField121");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "smallDatabaseNameField.nextFocusableComponent")) != null)) {
            _nsTextField0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField0");
        } else {
            _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField12");
        }
    }

    protected void _awaken() {
        super._awaken();
        _nsTextField18.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "setPassword", _nsTextField18), ""));
        _nsTextField0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "setUserName", _nsTextField0), ""));

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            _connect(_owner(), _nsCustomView0, "smallView");
        }

        if (_replacedObjects.objectForKey("_nsTextField18") == null) {
            _connect(_owner(), _nsTextField18, "smallPasswordField");
        }

        if (_replacedObjects.objectForKey("_nsTextField0") == null) {
            _connect(_owner(), _nsTextField0, "smallUserNameField");
        }

        if (_replacedObjects.objectForKey("_nsTextField1") == null) {
            _connect(_owner(), _nsTextField1, "smallDatabaseNameField");
        }

        _nsTextField11.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "setHostName", _nsTextField11), ""));

        if (_replacedObjects.objectForKey("_nsTextField12") == null) {
            _connect(_owner(), _nsTextField12, "smallPortField");
        }

        _nsTextField12.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "setPort", _nsTextField12), ""));

        if (_replacedObjects.objectForKey("_nsTextField11") == null) {
            _connect(_owner(), _nsTextField11, "smallHostNameField");
        }

        if (_replacedObjects.objectForKey("_nsTextField3") == null) {
            _connect(_owner(), _nsTextField3, "portField");
        }

        _nsTextField3.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "setPort", _nsTextField3), ""));

        if (_replacedObjects.objectForKey("_nsTextField4") == null) {
            _connect(_owner(), _nsTextField4, "databaseNameField");
        }

        if (_replacedObjects.objectForKey("_nsTextField5") == null) {
            _connect(_owner(), _nsTextField5, "userNameField");
        }

        if (_replacedObjects.objectForKey("_nsTextField19") == null) {
            _connect(_owner(), _nsTextField19, "passwordField");
        }

        if (_replacedObjects.objectForKey("_nsCustomView1") == null) {
            _connect(_owner(), _nsCustomView1, "view");
        }

        _nsTextField19.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "setPassword", _nsTextField19), ""));
        _nsTextField5.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "setUserName", _nsTextField5), ""));
        _nsTextField4.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "setDatabaseName", _nsTextField4), ""));
        _nsTextField2.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "setHostName", _nsTextField2), ""));

        if (_replacedObjects.objectForKey("_nsTextField2") == null) {
            _connect(_owner(), _nsTextField2, "hostNameField");
        }

        _nsTextField1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "setDatabaseName", _nsTextField1), ""));
    }

    protected void _init() {
        super._init();
        _setFontForComponent(_nsTextField17, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField17.setEditable(false);
        _nsTextField17.setOpaque(false);
        _nsTextField17.setText("Port:");
        _nsTextField17.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField17.setSelectable(false);
        _nsTextField17.setEnabled(true);
        _nsTextField17.setBorder(null);
        _setFontForComponent(_nsTextField16, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField16.setEditable(false);
        _nsTextField16.setOpaque(false);
        _nsTextField16.setText("Database Name:");
        _nsTextField16.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField16.setSelectable(false);
        _nsTextField16.setEnabled(true);
        _nsTextField16.setBorder(null);
        _setFontForComponent(_nsTextField15, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField15.setEditable(false);
        _nsTextField15.setOpaque(false);
        _nsTextField15.setText("Host Name:");
        _nsTextField15.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField15.setSelectable(false);
        _nsTextField15.setEnabled(true);
        _nsTextField15.setBorder(null);
        _setFontForComponent(_nsTextField14, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField14.setEditable(false);
        _nsTextField14.setOpaque(false);
        _nsTextField14.setText("Password:");
        _nsTextField14.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField14.setSelectable(false);
        _nsTextField14.setEnabled(true);
        _nsTextField14.setBorder(null);
        _setFontForComponent(_nsTextField13, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField13.setEditable(false);
        _nsTextField13.setOpaque(false);
        _nsTextField13.setText("User Name:");
        _nsTextField13.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField13.setSelectable(false);
        _nsTextField13.setEnabled(true);
        _nsTextField13.setBorder(null);

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            _connect(_nsCustomView0, _nsTextField11, "nextFocusableComponent");
        }

        if (_replacedObjects.objectForKey("_nsTextField12") == null) {
            _connect(_nsTextField12, _nsTextField1, "nextFocusableComponent");
        }

        if (_replacedObjects.objectForKey("_nsTextField12") == null) {
            _setFontForComponent(_nsTextField12, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField12.setEditable(true);
            _nsTextField12.setOpaque(true);
            _nsTextField12.setText("");
            _nsTextField12.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField12.setSelectable(true);
            _nsTextField12.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField11") == null) {
            _connect(_nsTextField11, _nsTextField12, "nextFocusableComponent");
        }

        if (_replacedObjects.objectForKey("_nsTextField11") == null) {
            _setFontForComponent(_nsTextField11, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField11.setEditable(true);
            _nsTextField11.setOpaque(true);
            _nsTextField11.setText("");
            _nsTextField11.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField11.setSelectable(true);
            _nsTextField11.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsCustomView1") == null) {
            _connect(_nsCustomView1, _nsTextField2, "nextFocusableComponent");
        }

        _setFontForComponent(_nsTextField10, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField10.setEditable(false);
        _nsTextField10.setOpaque(false);
        _nsTextField10.setText("Password:");
        _nsTextField10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField10.setSelectable(false);
        _nsTextField10.setEnabled(true);
        _nsTextField10.setBorder(null);
        _setFontForComponent(_nsTextField9, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField9.setEditable(false);
        _nsTextField9.setOpaque(false);
        _nsTextField9.setText("User Name:");
        _nsTextField9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField9.setSelectable(false);
        _nsTextField9.setEnabled(true);
        _nsTextField9.setBorder(null);
        _setFontForComponent(_nsTextField8, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField8.setEditable(false);
        _nsTextField8.setOpaque(false);
        _nsTextField8.setText("Database Name:");
        _nsTextField8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField8.setSelectable(false);
        _nsTextField8.setEnabled(true);
        _nsTextField8.setBorder(null);
        _setFontForComponent(_nsTextField7, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField7.setEditable(false);
        _nsTextField7.setOpaque(false);
        _nsTextField7.setText("Port:");
        _nsTextField7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField7.setSelectable(false);
        _nsTextField7.setEnabled(true);
        _nsTextField7.setBorder(null);
        _setFontForComponent(_nsTextField6, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField6.setEditable(false);
        _nsTextField6.setOpaque(false);
        _nsTextField6.setText("Host Name:");
        _nsTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField6.setSelectable(false);
        _nsTextField6.setEnabled(true);
        _nsTextField6.setBorder(null);

        if (_replacedObjects.objectForKey("_nsCustomView1") == null) {
            if (!(_nsCustomView1.getLayout() instanceof EOViewLayout)) { _nsCustomView1.setLayout(new EOViewLayout()); }
            _nsTextField6.setSize(94, 17);
            _nsTextField6.setLocation(8, 13);
            ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsTextField6, EOViewLayout.MinYMargin);
            _nsCustomView1.add(_nsTextField6);
            _nsTextField2.setSize(266, 19);
            _nsTextField2.setLocation(107, 10);
            ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.MinYMargin);
            _nsCustomView1.add(_nsTextField2);
            _nsTextField7.setSize(94, 17);
            _nsTextField7.setLocation(8, 35);
            ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsTextField7, EOViewLayout.MinYMargin);
            _nsCustomView1.add(_nsTextField7);
            _nsTextField3.setSize(266, 19);
            _nsTextField3.setLocation(107, 32);
            ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsTextField3, EOViewLayout.MinYMargin);
            _nsCustomView1.add(_nsTextField3);
            _nsTextField4.setSize(266, 19);
            _nsTextField4.setLocation(107, 54);
            ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsTextField4, EOViewLayout.MinYMargin);
            _nsCustomView1.add(_nsTextField4);
            _nsTextField8.setSize(94, 17);
            _nsTextField8.setLocation(8, 57);
            ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsTextField8, EOViewLayout.MinYMargin);
            _nsCustomView1.add(_nsTextField8);
            _nsTextField9.setSize(94, 17);
            _nsTextField9.setLocation(8, 79);
            ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsTextField9, EOViewLayout.MinYMargin);
            _nsCustomView1.add(_nsTextField9);
            _nsTextField5.setSize(266, 19);
            _nsTextField5.setLocation(107, 76);
            ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsTextField5, EOViewLayout.MinYMargin);
            _nsCustomView1.add(_nsTextField5);
            _nsTextField10.setSize(94, 17);
            _nsTextField10.setLocation(8, 101);
            ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsTextField10, EOViewLayout.MinYMargin);
            _nsCustomView1.add(_nsTextField10);
            _nsTextField19.setSize(266, 19);
            _nsTextField19.setLocation(107, 98);
            ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsTextField19, EOViewLayout.MinYMargin);
            _nsCustomView1.add(_nsTextField19);
        }

        if (_replacedObjects.objectForKey("_nsTextField19") == null) {
            _connect(_nsTextField19, _nsCustomView1, "nextFocusableComponent");
        }

        if (_replacedObjects.objectForKey("_nsTextField19") == null) {
            _setFontForComponent(_nsTextField19, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField19.setEditable(true);
            _nsTextField19.setOpaque(true);
            _nsTextField19.setText("");
            _nsTextField19.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField19.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField5") == null) {
            _connect(_nsTextField5, _nsTextField19, "nextFocusableComponent");
        }

        if (_replacedObjects.objectForKey("_nsTextField5") == null) {
            _setFontForComponent(_nsTextField5, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField5.setEditable(true);
            _nsTextField5.setOpaque(true);
            _nsTextField5.setText("");
            _nsTextField5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField5.setSelectable(true);
            _nsTextField5.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField4") == null) {
            _connect(_nsTextField4, _nsTextField5, "nextFocusableComponent");
        }

        if (_replacedObjects.objectForKey("_nsTextField4") == null) {
            _setFontForComponent(_nsTextField4, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField4.setEditable(true);
            _nsTextField4.setOpaque(true);
            _nsTextField4.setText("");
            _nsTextField4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField4.setSelectable(true);
            _nsTextField4.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField3") == null) {
            _connect(_nsTextField3, _nsTextField4, "nextFocusableComponent");
        }

        if (_replacedObjects.objectForKey("_nsTextField3") == null) {
            _setFontForComponent(_nsTextField3, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField3.setEditable(true);
            _nsTextField3.setOpaque(true);
            _nsTextField3.setText("");
            _nsTextField3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField3.setSelectable(true);
            _nsTextField3.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField2") == null) {
            _connect(_nsTextField2, _nsTextField3, "nextFocusableComponent");
        }

        if (_replacedObjects.objectForKey("_nsTextField2") == null) {
            _setFontForComponent(_nsTextField2, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField2.setEditable(true);
            _nsTextField2.setOpaque(true);
            _nsTextField2.setText("");
            _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField2.setSelectable(true);
            _nsTextField2.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField1") == null) {
            _connect(_nsTextField1, _nsTextField0, "nextFocusableComponent");
        }

        if (_replacedObjects.objectForKey("_nsTextField1") == null) {
            _setFontForComponent(_nsTextField1, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField1.setEditable(true);
            _nsTextField1.setOpaque(true);
            _nsTextField1.setText("");
            _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField1.setSelectable(true);
            _nsTextField1.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            if (!(_nsCustomView0.getLayout() instanceof EOViewLayout)) { _nsCustomView0.setLayout(new EOViewLayout()); }
            _nsTextField1.setSize(148, 19);
            _nsTextField1.setLocation(105, 54);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsTextField1);
            _nsTextField18.setSize(148, 19);
            _nsTextField18.setLocation(105, 98);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField18, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsTextField18);
            _nsTextField13.setSize(94, 17);
            _nsTextField13.setLocation(6, 79);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField13, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsTextField13);
            _nsTextField14.setSize(94, 17);
            _nsTextField14.setLocation(6, 101);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField14, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsTextField14);
            _nsTextField15.setSize(94, 17);
            _nsTextField15.setLocation(6, 13);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField15, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsTextField15);
            _nsTextField11.setSize(148, 19);
            _nsTextField11.setLocation(105, 10);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField11, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsTextField11);
            _nsTextField16.setSize(94, 17);
            _nsTextField16.setLocation(6, 57);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField16, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsTextField16);
            _nsTextField17.setSize(94, 17);
            _nsTextField17.setLocation(6, 35);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField17, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsTextField17);
            _nsTextField12.setSize(148, 19);
            _nsTextField12.setLocation(105, 32);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField12, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsTextField12);
            _nsTextField0.setSize(148, 19);
            _nsTextField0.setLocation(105, 76);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsTextField0);
        }

        if (_replacedObjects.objectForKey("_nsTextField18") == null) {
            _connect(_nsTextField18, _nsCustomView0, "nextFocusableComponent");
        }

        if (_replacedObjects.objectForKey("_nsTextField18") == null) {
            _setFontForComponent(_nsTextField18, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField18.setEditable(true);
            _nsTextField18.setOpaque(true);
            _nsTextField18.setText("");
            _nsTextField18.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField18.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField0") == null) {
            _connect(_nsTextField0, _nsTextField18, "nextFocusableComponent");
        }

        if (_replacedObjects.objectForKey("_nsTextField0") == null) {
            _setFontForComponent(_nsTextField0, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField0.setEditable(true);
            _nsTextField0.setOpaque(true);
            _nsTextField0.setText("");
            _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField0.setSelectable(true);
            _nsTextField0.setEnabled(true);
        }
    }
}
