// _DatabaseQuery_EOArchive_English.java
// Generated by EnterpriseObjects palette at Friday, October 22, 2004 1:00:53 PM US/Central

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.eointerface.swing.EOTable._EOTableColumn;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _DatabaseQuery_EOArchive_English extends com.webobjects.eoapplication.EOArchive {
    com.webobjects.eointerface.swing.EOFrame _eoFrame0;
    com.webobjects.eointerface.swing.EOTable _nsTableView0, _nsTableView1, _nsTableView2;
    com.webobjects.eointerface.swing.EOTable._EOTableColumn _eoTableColumn0, _eoTableColumn1, _eoTableColumn2, _eoTableColumn3;
    com.webobjects.eointerface.swing.EOTextArea _nsTextView0;
    com.webobjects.eointerface.swing.EOTextField _nsTextField0, _nsTextField1, _nsTextField2;
    com.webobjects.eointerface.swing.EOView _nsCustomView0, _nsCustomView1, _nsCustomView2, _nsCustomView3, _nsSplitView0, _nsSplitView1, _nsSplitView2;
    com.webobjects.foundation.NSNumberFormatter _nsNumberFormatter0;
    javax.swing.JButton _nsButton0, _nsButton1, _nsButton2, _nsButton3, _nsButton4, _nsButton5;
    javax.swing.JPanel _nsView0;

    public _DatabaseQuery_EOArchive_English(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _nsNumberFormatter0 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("0;-0"), "");
        _nsCustomView3 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsCustomView2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsCustomView1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsCustomView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsSplitView2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsSplitView1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsSplitView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "statusField")) != null)) {
            _nsTextField2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField2");
        } else {
            _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11");
        }

        _eoTableColumn3 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "queryTable")) != null)) {
            _nsTableView2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTable)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTableView2");
        } else {
            _nsTableView2 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "NSTableView");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "queryText")) != null)) {
            _nsTextView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextArea)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextView0");
        } else {
            _nsTextView0 = (com.webobjects.eointerface.swing.EOTextArea)_registered(new com.webobjects.eointerface.swing.EOTextArea(), "NSTextView");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "saveQueryButton")) != null)) {
            _nsButton5 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton5");
        } else {
            _nsButton5 = (javax.swing.JButton)_registered(new javax.swing.JButton("Save"), "NSButton1");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "removeQueryButton")) != null)) {
            _nsButton4 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton4");
        } else {
            _nsButton4 = (javax.swing.JButton)_registered(new javax.swing.JButton("Remove"), "NSButton11");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "previousQueryButton")) != null)) {
            _nsButton3 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton3");
        } else {
            _nsButton3 = (javax.swing.JButton)_registered(new javax.swing.JButton("-"), "NSButton3");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "nextQueryButton")) != null)) {
            _nsButton2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton2");
        } else {
            _nsButton2 = (javax.swing.JButton)_registered(new javax.swing.JButton("+"), "NSButton31");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "exportQueryButton")) != null)) {
            _nsButton1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton1");
        } else {
            _nsButton1 = (javax.swing.JButton)_registered(new javax.swing.JButton("Export..."), "NSButton2");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "executeQueryButton")) != null)) {
            _nsButton0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton0");
        } else {
            _nsButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton("Execute"), "NSButton");
        }

        _eoTableColumn2 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn1");
        _eoTableColumn1 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "dataTable")) != null)) {
            _nsTableView1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTable)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTableView1");
        } else {
            _nsTableView1 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "NSTableView");
        }

        _eoTableColumn0 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "entityTable")) != null)) {
            _nsTableView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTable)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTableView0");
        } else {
            _nsTableView0 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "NSTableView");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "maxFetchField")) != null)) {
            _nsTextField1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField1");
        } else {
            _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField");
        }

        _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "window")) != null)) {
            _eoFrame0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame0");
        } else {
            _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Window");
        }

        _nsView0 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _connect(_eoFrame0, _owner(), "delegate");
        }

        if (_replacedObjects.objectForKey("_nsTextField2") == null) {
            _connect(_owner(), _nsTextField2, "statusField");
        }

        if (_replacedObjects.objectForKey("_nsTextField1") == null) {
            _connect(_owner(), _nsTextField1, "maxFetchField");
        }

        _nsTableView2.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "selectQuery", _nsTableView2), ""));

        if (_replacedObjects.objectForKey("_nsTableView2") == null) {
            _connect(_nsTableView2, _owner(), "delegate");
        }

        if (_replacedObjects.objectForKey("_nsTableView2") == null) {
            _connect(_nsTableView2, _owner(), "dataSource");
        }

        if (_replacedObjects.objectForKey("_nsTableView2") == null) {
            _connect(_owner(), _nsTableView2, "queryTable");
        }

        if (_replacedObjects.objectForKey("_nsTextView0") == null) {
            _connect(_nsTextView0, _owner(), "delegate");
        }

        if (_replacedObjects.objectForKey("_nsTextView0") == null) {
            _connect(_owner(), _nsTextView0, "queryText");
        }

        _nsButton5.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "saveQuery", _nsButton5), ""));

        if (_replacedObjects.objectForKey("_nsButton5") == null) {
            _connect(_owner(), _nsButton5, "saveQueryButton");
        }

        _nsButton4.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "removeQuery", _nsButton4), ""));

        if (_replacedObjects.objectForKey("_nsButton4") == null) {
            _connect(_owner(), _nsButton4, "removeQueryButton");
        }

        _nsButton3.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "previousQuery", _nsButton3), ""));

        if (_replacedObjects.objectForKey("_nsButton3") == null) {
            _connect(_owner(), _nsButton3, "previousQueryButton");
        }

        _nsButton2.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "nextQuery", _nsButton2), ""));

        if (_replacedObjects.objectForKey("_nsButton2") == null) {
            _connect(_owner(), _nsButton2, "nextQueryButton");
        }

        _nsButton1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "exportQuery", _nsButton1), ""));

        if (_replacedObjects.objectForKey("_nsButton1") == null) {
            _connect(_owner(), _nsButton1, "exportQueryButton");
        }

        _nsButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "executeQuery", _nsButton0), ""));

        if (_replacedObjects.objectForKey("_nsButton0") == null) {
            _connect(_owner(), _nsButton0, "executeQueryButton");
        }

        if (_replacedObjects.objectForKey("_nsTableView1") == null) {
            _connect(_nsTableView1, _owner(), "delegate");
        }

        if (_replacedObjects.objectForKey("_nsTableView1") == null) {
            _connect(_nsTableView1, _owner(), "dataSource");
        }

        if (_replacedObjects.objectForKey("_nsTableView1") == null) {
            _connect(_owner(), _nsTableView1, "dataTable");
        }

        _nsTableView0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "selectEntity", _nsTableView0), ""));

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _connect(_nsTableView0, _owner(), "dataSource");
        }

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _connect(_nsTableView0, _owner(), "delegate");
        }

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _connect(_owner(), _nsTableView0, "entityTable");
        }

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _connect(_owner(), _eoFrame0, "window");
        }

        _nsTextField1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "setMaxRowsToFetch", _nsTextField1), ""));
    }

    protected void _init() {
        super._init();
        _nsNumberFormatter0.setMinimum(new java.math.BigDecimal("1"));
        if (!(_nsCustomView3.getLayout() instanceof EOViewLayout)) { _nsCustomView3.setLayout(new EOViewLayout()); }
        _nsButton5.setSize(92, 22);
        _nsButton5.setLocation(0, -2);
        ((EOViewLayout)_nsCustomView3.getLayout()).setAutosizingMask(_nsButton5, EOViewLayout.MinYMargin);
        _nsCustomView3.add(_nsButton5);
        _nsButton4.setSize(92, 22);
        _nsButton4.setLocation(97, -2);
        ((EOViewLayout)_nsCustomView3.getLayout()).setAutosizingMask(_nsButton4, EOViewLayout.MinYMargin);
        _nsCustomView3.add(_nsButton4);
        if (!(_nsCustomView2.getLayout() instanceof EOViewLayout)) { _nsCustomView2.setLayout(new EOViewLayout()); }
        _nsButton0.setSize(92, 22);
        _nsButton0.setLocation(0, -2);
        ((EOViewLayout)_nsCustomView2.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MinYMargin);
        _nsCustomView2.add(_nsButton0);
        _nsButton1.setSize(92, 22);
        _nsButton1.setLocation(97, -2);
        ((EOViewLayout)_nsCustomView2.getLayout()).setAutosizingMask(_nsButton1, EOViewLayout.MinYMargin);
        _nsCustomView2.add(_nsButton1);
        if (!(_nsCustomView1.getLayout() instanceof EOViewLayout)) { _nsCustomView1.setLayout(new EOViewLayout()); }
        _nsButton3.setSize(25, 25);
        _nsButton3.setLocation(3, 0);
        ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsButton3, EOViewLayout.MinYMargin);
        _nsCustomView1.add(_nsButton3);
        _nsButton2.setSize(25, 25);
        _nsButton2.setLocation(31, 0);
        ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsButton2, EOViewLayout.MinYMargin);
        _nsCustomView1.add(_nsButton2);
        if (!(_nsCustomView0.getLayout() instanceof EOViewLayout)) { _nsCustomView0.setLayout(new EOViewLayout()); }
        _nsTextView0.setSize(672, 122);
        _nsTextView0.setLocation(0, 28);
        ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsCustomView0.add(_nsTextView0);
        _nsCustomView1.setSize(60, 25);
        _nsCustomView1.setLocation(300, 0);
        ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsCustomView1, EOViewLayout.MinXMargin | EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsCustomView0.add(_nsCustomView1);
        _nsCustomView2.setSize(186, 24);
        _nsCustomView2.setLocation(474, 1);
        ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsCustomView2, EOViewLayout.MinXMargin | EOViewLayout.MaxYMargin);
        _nsCustomView0.add(_nsCustomView2);
        _nsCustomView3.setSize(186, 24);
        _nsCustomView3.setLocation(0, 1);
        ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsCustomView3, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsCustomView0.add(_nsCustomView3);
        if (!(_nsSplitView2.getLayout() instanceof EOViewLayout)) { _nsSplitView2.setLayout(new EOViewLayout()); }
        _nsTableView2.setSize(136, 150);
        _nsTableView2.setLocation(0, 0);
        ((EOViewLayout)_nsSplitView2.getLayout()).setAutosizingMask(_nsTableView2, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsSplitView2.add(_nsTableView2);
        _nsCustomView0.setSize(672, 150);
        _nsCustomView0.setLocation(145, 0);
        ((EOViewLayout)_nsSplitView2.getLayout()).setAutosizingMask(_nsCustomView0, EOViewLayout.MinYMargin);
        _nsSplitView2.add(_nsCustomView0);
        if (!(_nsSplitView1.getLayout() instanceof EOViewLayout)) { _nsSplitView1.setLayout(new EOViewLayout()); }
        _nsTableView0.setSize(136, 468);
        _nsTableView0.setLocation(0, 0);
        ((EOViewLayout)_nsSplitView1.getLayout()).setAutosizingMask(_nsTableView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsSplitView1.add(_nsTableView0);
        _nsTableView1.setSize(672, 468);
        _nsTableView1.setLocation(145, 0);
        ((EOViewLayout)_nsSplitView1.getLayout()).setAutosizingMask(_nsTableView1, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsSplitView1.add(_nsTableView1);
        if (!(_nsSplitView0.getLayout() instanceof EOViewLayout)) { _nsSplitView0.setLayout(new EOViewLayout()); }
        _nsSplitView1.setSize(817, 468);
        _nsSplitView1.setLocation(0, 0);
        ((EOViewLayout)_nsSplitView0.getLayout()).setAutosizingMask(_nsSplitView1, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsSplitView0.add(_nsSplitView1);
        _nsSplitView2.setSize(817, 150);
        _nsSplitView2.setLocation(0, 477);
        ((EOViewLayout)_nsSplitView0.getLayout()).setAutosizingMask(_nsSplitView2, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsSplitView0.add(_nsSplitView2);

        if (_replacedObjects.objectForKey("_nsTextField2") == null) {
            _setFontForComponent(_nsTextField2, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField2.setEditable(false);
            _nsTextField2.setOpaque(false);
            _nsTextField2.setText("");
            _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField2.setSelectable(false);
            _nsTextField2.setEnabled(true);
            _nsTextField2.setBorder(null);
        }

        _eoTableColumn3.setMinWidth(40);
        _eoTableColumn3.setMaxWidth(1000);
        _eoTableColumn3.setPreferredWidth(116);
        _eoTableColumn3.setWidth(116);
        _eoTableColumn3.setResizable(true);
        _eoTableColumn3.setHeaderValue("Queries");

        if (_replacedObjects.objectForKey("_nsTableView2") == null) {
            _nsTableView2.table().addColumn(_eoTableColumn3);
            _setFontForComponent(_nsTableView2.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
            _nsTableView2.table().setRowHeight(17);
        }

        if (_replacedObjects.objectForKey("_nsTextView0") == null) {
            _nsTextView0.setEditable(true);
            _nsTextView0.setOpaque(true);
            _nsTextView0.setText("");
        }

        if (_replacedObjects.objectForKey("_nsButton5") == null) {
            _setFontForComponent(_nsButton5, "Lucida Grande", 11, Font.PLAIN);
            _nsButton5.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton4") == null) {
            _setFontForComponent(_nsButton4, "Lucida Grande", 11, Font.PLAIN);
            _nsButton4.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton3") == null) {
            _setFontForComponent(_nsButton3, "Lucida Grande", 12, Font.PLAIN);
            _nsButton3.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton2") == null) {
            _setFontForComponent(_nsButton2, "Lucida Grande", 12, Font.PLAIN);
            _nsButton2.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton1") == null) {
            _setFontForComponent(_nsButton1, "Lucida Grande", 11, Font.PLAIN);
            _nsButton1.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton0") == null) {
            _setFontForComponent(_nsButton0, "Lucida Grande", 11, Font.PLAIN);
            _nsButton0.setMargin(new Insets(0, 2, 0, 2));
        }

        _eoTableColumn2.setMinWidth(40);
        _eoTableColumn2.setMaxWidth(1000);
        _eoTableColumn2.setPreferredWidth(609);
        _eoTableColumn2.setWidth(609);
        _eoTableColumn2.setResizable(true);
        _eoTableColumn2.setHeaderValue("");
        if ((_eoTableColumn2.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn2.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn1.setMinWidth(40);
        _eoTableColumn1.setMaxWidth(1000);
        _eoTableColumn1.setPreferredWidth(40);
        _eoTableColumn1.setWidth(40);
        _eoTableColumn1.setResizable(true);
        _eoTableColumn1.setHeaderValue("");
        if ((_eoTableColumn1.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn1.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }

        if (_replacedObjects.objectForKey("_nsTableView1") == null) {
            _nsTableView1.table().addColumn(_eoTableColumn1);
            _nsTableView1.table().addColumn(_eoTableColumn2);
            _setFontForComponent(_nsTableView1.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
            _nsTableView1.table().setRowHeight(17);
        }

        _eoTableColumn0.setMinWidth(40);
        _eoTableColumn0.setMaxWidth(1000);
        _eoTableColumn0.setPreferredWidth(116);
        _eoTableColumn0.setWidth(116);
        _eoTableColumn0.setResizable(false);
        _eoTableColumn0.setHeaderValue("Entities");

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _nsTableView0.table().addColumn(_eoTableColumn0);
            _setFontForComponent(_nsTableView0.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
            _nsTableView0.table().setRowHeight(17);
        }

        if (_replacedObjects.objectForKey("_nsTextField1") == null) {
            _setFontForComponent(_nsTextField1, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField1.setEditable(true);
            _nsTextField1.setOpaque(true);
            _nsTextField1.setText("5000");
            _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField1.setSelectable(true);
            _nsTextField1.setEnabled(true);
        }

        _setFontForComponent(_nsTextField0, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField0.setEditable(false);
        _nsTextField0.setOpaque(false);
        _nsTextField0.setText("Max number of rows to fetch:");
        _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField0.setSelectable(false);
        _nsTextField0.setEnabled(true);
        _nsTextField0.setBorder(null);
        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsTextField0.setSize(201, 14);
        _nsTextField0.setLocation(504, 5);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MinXMargin | EOViewLayout.MaxYMargin);
        _nsView0.add(_nsTextField0);
        _nsTextField1.setSize(91, 19);
        _nsTextField1.setLocation(710, 2);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.MinXMargin | EOViewLayout.MaxYMargin);
        _nsView0.add(_nsTextField1);
        _nsTextField2.setSize(366, 14);
        _nsTextField2.setLocation(-1, 7);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin);
        _nsView0.add(_nsTextField2);
        _nsSplitView0.setSize(817, 627);
        _nsSplitView0.setLocation(-8, 28);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsSplitView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsView0.add(_nsSplitView0);

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _nsView0.setSize(801, 648);
            _eoFrame0.setTitle("Data Browser");
            _eoFrame0.setLocation(415, 244);
            _eoFrame0.setSize(801, 648);
        }
    }
}
