// _EditorEntity_EOArchive_English.java
// Generated by EnterpriseObjects palette at Friday, October 15, 2004 1:33:18 PM US/Central

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.eointerface.swing.EOTable._EOTableColumn;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _EditorEntity_EOArchive_English extends com.webobjects.eoapplication.EOArchive {
    com.webobjects.eointerface.swing.EOTable _nsTableView0, _nsTableView1;
    com.webobjects.eointerface.swing.EOTable._EOTableColumn _eoTableColumn0, _eoTableColumn1, _eoTableColumn10, _eoTableColumn11, _eoTableColumn12, _eoTableColumn13, _eoTableColumn14, _eoTableColumn15, _eoTableColumn16, _eoTableColumn17, _eoTableColumn18, _eoTableColumn19, _eoTableColumn2, _eoTableColumn20, _eoTableColumn21, _eoTableColumn22, _eoTableColumn3, _eoTableColumn4, _eoTableColumn5, _eoTableColumn6, _eoTableColumn7, _eoTableColumn8, _eoTableColumn9;
    com.webobjects.eointerface.swing.EOTextField _eoTextField0, _eoTextField1, _eoTextField2, _eoTextField3, _eoTextField4, _nsTextField0, _nsTextField1;
    com.webobjects.eointerface.swing.EOView _nsCustomView0, _nsCustomView1, _nsCustomView2, _nsSplitView0;
    com.webobjects.foundation.NSNumberFormatter _nsNumberFormatter0, _nsNumberFormatter1, _nsNumberFormatter2;
    javax.swing.JButton _jButton0, _jButton1, _jButton2, _jButton3, _jButton4;
    javax.swing.JCheckBox _jCheckBox0;

    public _EditorEntity_EOArchive_English(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _eoTextField4 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _jButton4 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "");
        _jButton3 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "");
        _jCheckBox0 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox(""), "");
        _eoTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _nsNumberFormatter2 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("#,##0;-#,##0"), "");
        _jButton2 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "");
        _nsNumberFormatter1 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("#,##0;-#,##0"), "");
        _nsNumberFormatter0 = (com.webobjects.foundation.NSNumberFormatter)_registered(new com.webobjects.foundation.NSNumberFormatter("#,##0;-#,##0"), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "entityRelationshipsText")) != null)) {
            _nsTextField1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField1");
        } else {
            _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");
        }

        _nsCustomView2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "entityAttributesText")) != null)) {
            _nsTextField0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField0");
        } else {
            _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11");
        }

        _eoTableColumn22 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn21 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn20 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn19 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn18 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn17 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn16 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn15 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn14 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn13 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn12 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn11 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn1");
        _eoTableColumn10 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "entityAttributesTable")) != null)) {
            _nsTableView1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTable)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTableView1");
        } else {
            _nsTableView1 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "NSTableView");
        }

        _nsCustomView1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsSplitView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "view")) != null)) {
            _nsCustomView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView0");
        } else {
            _nsCustomView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "View");
        }

        _eoTableColumn9 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn8 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn7 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn6 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn5 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn1");
        _eoTableColumn4 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "entityRelationshipsTable")) != null)) {
            _nsTableView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTable)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTableView0");
        } else {
            _nsTableView0 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "NSTableView");
        }

        _jButton1 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "");
        _eoTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTableColumn3 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn2 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _eoTableColumn1 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
        _jButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "");
        _eoTableColumn0 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "");
    }

    protected void _awaken() {
        super._awaken();
        _nsTableView0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "selectRelationship", _nsTableView0), ""));

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _connect(_nsTableView0, _owner(), "delegate");
        }

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _connect(_owner(), _nsTableView0, "entityRelationshipsTable");
        }

        if (_replacedObjects.objectForKey("_nsTextField1") == null) {
            _connect(_owner(), _nsTextField1, "entityRelationshipsText");
        }

        if (_replacedObjects.objectForKey("_nsTextField0") == null) {
            _connect(_owner(), _nsTextField0, "entityAttributesText");
        }

        if (_replacedObjects.objectForKey("_nsTableView1") == null) {
            _connect(_owner(), _nsTableView1, "entityAttributesTable");
        }

        _nsTableView1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "selectAttribute", _nsTableView1), ""));

        if (_replacedObjects.objectForKey("_nsTableView1") == null) {
            _connect(_nsTableView1, _owner(), "delegate");
        }

        if (_replacedObjects.objectForKey("_nsTableView1") == null) {
            _connect(_nsTableView1, _owner(), "dataSource");
        }

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            _connect(_owner(), _nsCustomView0, "view");
        }

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _connect(_nsTableView0, _owner(), "dataSource");
        }
    }

    protected void _init() {
        super._init();
        _setFontForComponent(_eoTextField4, "Lucida Grande", 12, Font.PLAIN);
        _setFontForComponent(_eoTextField3, "Lucida Grande", 12, Font.PLAIN);
        _setFontForComponent(_jButton4, "Lucida Grande", 12, Font.PLAIN);
        _jButton4.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jButton3, "Lucida Grande", 12, Font.PLAIN);
        _jButton3.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_jCheckBox0, "Lucida Grande", 12, Font.PLAIN);
        _setFontForComponent(_eoTextField2, "Lucida Grande", 12, Font.PLAIN);
        _setFontForComponent(_eoTextField1, "Lucida Grande", 12, Font.PLAIN);
        
        _setFontForComponent(_jButton2, "Lucida Grande", 12, Font.PLAIN);
        _jButton2.setMargin(new Insets(0, 2, 0, 2));
        
        

        if (_replacedObjects.objectForKey("_nsTextField1") == null) {
            _setFontForComponent(_nsTextField1, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField1.setEditable(false);
            _nsTextField1.setOpaque(false);
            _nsTextField1.setText("Entity Relationships");
            _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField1.setSelectable(false);
            _nsTextField1.setEnabled(true);
            _nsTextField1.setBorder(null);
        }

        if (!(_nsCustomView2.getLayout() instanceof EOViewLayout)) { _nsCustomView2.setLayout(new EOViewLayout()); }
        _nsTableView0.setSize(613, 116);
        _nsTableView0.setLocation(0, 16);
        ((EOViewLayout)_nsCustomView2.getLayout()).setAutosizingMask(_nsTableView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsCustomView2.add(_nsTableView0);
        _nsTextField1.setSize(616, 14);
        _nsTextField1.setLocation(1, 0);
        ((EOViewLayout)_nsCustomView2.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
        _nsCustomView2.add(_nsTextField1);

        if (_replacedObjects.objectForKey("_nsTextField0") == null) {
            _setFontForComponent(_nsTextField0, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField0.setEditable(false);
            _nsTextField0.setOpaque(false);
            _nsTextField0.setText("Entity Attributes");
            _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField0.setSelectable(false);
            _nsTextField0.setEnabled(true);
            _nsTextField0.setBorder(null);
        }

        _eoTableColumn22.setMinWidth(76);
        _eoTableColumn22.setMaxWidth(1000);
        _eoTableColumn22.setPreferredWidth(108);
        _eoTableColumn22.setWidth(108);
        _eoTableColumn22.setResizable(true);
        _eoTableColumn22.setHeaderValue("Write Format");
        _eoTableColumn21.setMinWidth(10);
        _eoTableColumn21.setMaxWidth(1000);
        _eoTableColumn21.setPreferredWidth(108);
        _eoTableColumn21.setWidth(108);
        _eoTableColumn21.setResizable(true);
        _eoTableColumn21.setHeaderValue("Read Format");
        _eoTableColumn20.setMinWidth(10);
        _eoTableColumn20.setMaxWidth(1000);
        _eoTableColumn20.setPreferredWidth(108);
        _eoTableColumn20.setWidth(108);
        _eoTableColumn20.setResizable(true);
        _eoTableColumn20.setHeaderValue("Prototype");
        _eoTableColumn19.setMinWidth(10);
        _eoTableColumn19.setMaxWidth(1000);
        _eoTableColumn19.setPreferredWidth(48);
        _eoTableColumn19.setWidth(48);
        _eoTableColumn19.setResizable(true);
        _eoTableColumn19.setHeaderValue("Precision");
        if ((_eoTableColumn19.getCellRenderer() instanceof DefaultTableCellRenderer) || (_eoTableColumn19.getCellRenderer() == null)) {
        	DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        	renderer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        	_eoTableColumn19.setCellRenderer(renderer);
        }
        _eoTableColumn18.setMinWidth(10);
        _eoTableColumn18.setMaxWidth(1000);
        _eoTableColumn18.setPreferredWidth(48);
        _eoTableColumn18.setWidth(48);
        _eoTableColumn18.setResizable(true);
        _eoTableColumn18.setHeaderValue("Scale");
        if ((_eoTableColumn18.getCellRenderer() instanceof DefaultTableCellRenderer) || (_eoTableColumn18.getCellRenderer() == null)) {
        	DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        	renderer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        	_eoTableColumn18.setCellRenderer(renderer);
        }
        _eoTableColumn17.setMinWidth(10);
        _eoTableColumn17.setMaxWidth(1000);
        _eoTableColumn17.setPreferredWidth(48);
        _eoTableColumn17.setWidth(48);
        _eoTableColumn17.setResizable(true);
        _eoTableColumn17.setHeaderValue("Width");
        if ((_eoTableColumn17.getCellRenderer() instanceof DefaultTableCellRenderer) || (_eoTableColumn17.getCellRenderer() == null)) {
        	DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        	renderer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        	_eoTableColumn17.setCellRenderer(renderer);
        }
        _eoTableColumn16.setMinWidth(10);
        _eoTableColumn16.setMaxWidth(1000);
        _eoTableColumn16.setPreferredWidth(72);
        _eoTableColumn16.setWidth(72);
        _eoTableColumn16.setResizable(true);
        _eoTableColumn16.setHeaderValue("External Type");
        _eoTableColumn15.setMinWidth(10);
        _eoTableColumn15.setMaxWidth(1000);
        _eoTableColumn15.setPreferredWidth(72);
        _eoTableColumn15.setWidth(72);
        _eoTableColumn15.setResizable(true);
        _eoTableColumn15.setHeaderValue("Value Class");
        _eoTableColumn14.setMinWidth(10);
        _eoTableColumn14.setMaxWidth(1000);
        _eoTableColumn14.setPreferredWidth(108);
        _eoTableColumn14.setWidth(108);
        _eoTableColumn14.setResizable(true);
        _eoTableColumn14.setHeaderValue("Column");
        _eoTableColumn13.setMinWidth(10);
        _eoTableColumn13.setMaxWidth(1000);
        _eoTableColumn13.setPreferredWidth(108);
        _eoTableColumn13.setWidth(108);
        _eoTableColumn13.setResizable(true);
        _eoTableColumn13.setHeaderValue("Name");
        _eoTableColumn12.setMinWidth(15);
        _eoTableColumn12.setMaxWidth(15);
        _eoTableColumn12.setPreferredWidth(15);
        _eoTableColumn12.setWidth(15);
        _eoTableColumn12.setResizable(true);
        _eoTableColumn12.setHeaderValue("Locking Attribute");
        if ((_eoTableColumn12.getCellRenderer() instanceof DefaultTableCellRenderer) || (_eoTableColumn12.getCellRenderer() == null)) {
        	DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        	renderer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        	_eoTableColumn12.setCellRenderer(renderer);
        }
        _eoTableColumn11.setMinWidth(15);
        _eoTableColumn11.setMaxWidth(15);
        _eoTableColumn11.setPreferredWidth(15);
        _eoTableColumn11.setWidth(15);
        _eoTableColumn11.setResizable(true);
        _eoTableColumn11.setHeaderValue("Class Property");
        if ((_eoTableColumn11.getCellRenderer() instanceof DefaultTableCellRenderer) || (_eoTableColumn11.getCellRenderer() == null)) {
        	DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        	renderer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        	_eoTableColumn11.setCellRenderer(renderer);
        }
        _eoTableColumn10.setMinWidth(15);
        _eoTableColumn10.setMaxWidth(15);
        _eoTableColumn10.setPreferredWidth(15);
        _eoTableColumn10.setWidth(15);
        _eoTableColumn10.setResizable(true);
        _eoTableColumn10.setHeaderValue("Primary Key");
        if ((_eoTableColumn10.getCellRenderer() instanceof DefaultTableCellRenderer) || (_eoTableColumn10.getCellRenderer() == null)) {
        	DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        	renderer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        	_eoTableColumn10.setCellRenderer(renderer);
        }

        if (_replacedObjects.objectForKey("_nsTableView1") == null) {
            _nsTableView1.table().addColumn(_eoTableColumn10);
            _nsTableView1.table().addColumn(_eoTableColumn11);
            _nsTableView1.table().addColumn(_eoTableColumn12);
            _nsTableView1.table().addColumn(_eoTableColumn0);
            _nsTableView1.table().addColumn(_eoTableColumn13);
            _nsTableView1.table().addColumn(_eoTableColumn14);
            _nsTableView1.table().addColumn(_eoTableColumn15);
            _nsTableView1.table().addColumn(_eoTableColumn16);
            _nsTableView1.table().addColumn(_eoTableColumn17);
            _nsTableView1.table().addColumn(_eoTableColumn18);
            _nsTableView1.table().addColumn(_eoTableColumn19);
            _nsTableView1.table().addColumn(_eoTableColumn2);
            _nsTableView1.table().addColumn(_eoTableColumn3);
            _nsTableView1.table().addColumn(_eoTableColumn20);
            _nsTableView1.table().addColumn(_eoTableColumn21);
            _nsTableView1.table().addColumn(_eoTableColumn22);
            _setFontForComponent(_nsTableView1.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
            _nsTableView1.table().setRowHeight(17);
        }

        if (!(_nsCustomView1.getLayout() instanceof EOViewLayout)) { _nsCustomView1.setLayout(new EOViewLayout()); }
        _nsTableView1.setSize(613, 488);
        _nsTableView1.setLocation(0, 18);
        ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsTableView1, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsCustomView1.add(_nsTableView1);
        _nsTextField0.setSize(616, 14);
        _nsTextField0.setLocation(1, 2);
        ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
        _nsCustomView1.add(_nsTextField0);
        if (!(_nsSplitView0.getLayout() instanceof EOViewLayout)) { _nsSplitView0.setLayout(new EOViewLayout()); }
        _nsCustomView1.setSize(616, 506);
        _nsCustomView1.setLocation(0, 0);
        ((EOViewLayout)_nsSplitView0.getLayout()).setAutosizingMask(_nsCustomView1, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsSplitView0.add(_nsCustomView1);
        _nsCustomView2.setSize(616, 132);
        _nsCustomView2.setLocation(0, 515);
        ((EOViewLayout)_nsSplitView0.getLayout()).setAutosizingMask(_nsCustomView2, EOViewLayout.MinYMargin);
        _nsSplitView0.add(_nsCustomView2);

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            if (!(_nsCustomView0.getLayout() instanceof EOViewLayout)) { _nsCustomView0.setLayout(new EOViewLayout()); }
            _nsSplitView0.setSize(616, 647);
            _nsSplitView0.setLocation(0, 0);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsSplitView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
            _nsCustomView0.add(_nsSplitView0);
        }

        _eoTableColumn9.setMinWidth(60);
        _eoTableColumn9.setMaxWidth(1000);
        _eoTableColumn9.setPreferredWidth(151);
        _eoTableColumn9.setWidth(151);
        _eoTableColumn9.setResizable(true);
        _eoTableColumn9.setHeaderValue("Definition");
        _eoTableColumn8.setMinWidth(10);
        _eoTableColumn8.setMaxWidth(1000);
        _eoTableColumn8.setPreferredWidth(108);
        _eoTableColumn8.setWidth(108);
        _eoTableColumn8.setResizable(true);
        _eoTableColumn8.setHeaderValue("Source Attribute");
        _eoTableColumn7.setMinWidth(10);
        _eoTableColumn7.setMaxWidth(1000);
        _eoTableColumn7.setPreferredWidth(108);
        _eoTableColumn7.setWidth(108);
        _eoTableColumn7.setResizable(true);
        _eoTableColumn7.setHeaderValue("Destination");
        _eoTableColumn6.setMinWidth(10);
        _eoTableColumn6.setMaxWidth(1000);
        _eoTableColumn6.setPreferredWidth(108);
        _eoTableColumn6.setWidth(108);
        _eoTableColumn6.setResizable(true);
        _eoTableColumn6.setHeaderValue("Name");
        _eoTableColumn5.setMinWidth(15);
        _eoTableColumn5.setMaxWidth(15);
        _eoTableColumn5.setPreferredWidth(15);
        _eoTableColumn5.setWidth(15);
        _eoTableColumn5.setResizable(true);
        _eoTableColumn5.setHeaderValue("Class Property");
        if ((_eoTableColumn5.getCellRenderer() instanceof DefaultTableCellRenderer) || (_eoTableColumn5.getCellRenderer() == null)) {
        	DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        	renderer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        	_eoTableColumn5.setCellRenderer(renderer);
        }
        _eoTableColumn4.setMinWidth(15);
        _eoTableColumn4.setMaxWidth(15);
        _eoTableColumn4.setPreferredWidth(15);
        _eoTableColumn4.setWidth(15);
        _eoTableColumn4.setResizable(true);
        _eoTableColumn4.setHeaderValue("Type");
        if ((_eoTableColumn4.getCellRenderer() instanceof DefaultTableCellRenderer) || (_eoTableColumn4.getCellRenderer() == null)) {
        	DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        	renderer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        	_eoTableColumn4.setCellRenderer(renderer);
        }

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _nsTableView0.table().addColumn(_eoTableColumn4);
            _nsTableView0.table().addColumn(_eoTableColumn5);
            _nsTableView0.table().addColumn(_eoTableColumn6);
            _nsTableView0.table().addColumn(_eoTableColumn7);
            _nsTableView0.table().addColumn(_eoTableColumn8);
            _nsTableView0.table().addColumn(_eoTableColumn1);
            _nsTableView0.table().addColumn(_eoTableColumn9);
            _setFontForComponent(_nsTableView0.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
            _nsTableView0.table().setRowHeight(17);
        }

        _setFontForComponent(_jButton1, "Lucida Grande", 12, Font.PLAIN);
        _jButton1.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_eoTextField0, "Lucida Grande", 12, Font.PLAIN);
        _eoTableColumn3.setMinWidth(10);
        _eoTableColumn3.setMaxWidth(1000);
        _eoTableColumn3.setPreferredWidth(108);
        _eoTableColumn3.setWidth(108);
        _eoTableColumn3.setResizable(true);
        _eoTableColumn3.setHeaderValue("Definition");
        _eoTableColumn2.setMinWidth(10);
        _eoTableColumn2.setMaxWidth(1000);
        _eoTableColumn2.setPreferredWidth(20);
        _eoTableColumn2.setWidth(20);
        _eoTableColumn2.setResizable(true);
        _eoTableColumn2.setHeaderValue("Value Type");
        if ((_eoTableColumn2.getCellRenderer() instanceof DefaultTableCellRenderer) || (_eoTableColumn2.getCellRenderer() == null)) {
        	DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        	renderer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        	_eoTableColumn2.setCellRenderer(renderer);
        }
        _eoTableColumn1.setMinWidth(10);
        _eoTableColumn1.setMaxWidth(1000);
        _eoTableColumn1.setPreferredWidth(108);
        _eoTableColumn1.setWidth(108);
        _eoTableColumn1.setResizable(true);
        _eoTableColumn1.setHeaderValue("Destination Attribute");
        _setFontForComponent(_jButton0, "Lucida Grande", 12, Font.PLAIN);
        _jButton0.setMargin(new Insets(0, 2, 0, 2));
        _eoTableColumn0.setMinWidth(15);
        _eoTableColumn0.setMaxWidth(15);
        _eoTableColumn0.setPreferredWidth(15);
        _eoTableColumn0.setWidth(15);
        _eoTableColumn0.setResizable(true);
        _eoTableColumn0.setHeaderValue("Nullable");
    }
}
